=== stevendatle/XMLAssignment2/xml/users.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="userid" type="xs:positiveInteger"/>
              <xs:element name="usertype" type="xs:string"/>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="username" type="xs:string"/>
              <xs:element name="password" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== stevendatle/XMLAssignment2/xml/users.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- DATA STRUCTURE FOR USERS, CLIENT + ADMIN -->

<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
  <user>
    <userid>0025</userid>
    <usertype>Client</usertype>
    <name>Dylan Marley</name>
    <username>client</username>
    <password>123</password>
  </user>
  <user>
    <userid>0001</userid>
    <usertype>Admin</usertype>
    <name>Morgan Freeman</name>
    <username>admin</username>
    <password>pass</password>
  </user>
</users>
